// @ts-nocheck
// tslint:disable
/**
 * beacon
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, { AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { InlineResponse2002 } from '../models';
type CustomPromise<T>={
    code:number,
    success:boolean,
    msg:string,
    data:T,
    time:string,
    error?:string[]
}
/**
 * HomeApi - axios parameter creator
 * @export
 */
export const HomeApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 获取首页
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiHomeGet: async (options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/home`;

            const globalImportUrl={
                parse:(url:string)=>{
                   const query:{[key in string] : string}={}

                   const [path , paramsString] = url.split("?")
                   const params = paramsString?.split('&') || []
                   params.forEach(t=>{
                        const [ k , v ] = t.split('=')
                        query[k] = v
                   })
                   return {
                        query,
                        path
                    }
                },
                format:(obj:{path:string,query:{[key in string]:string}})=>{
                    const {path,query}=obj
                    const queryStringify = Object.entries(query).map(([k,v])=>`${k}=${v}`).join('&')
                    if(!queryStringify) return path
                    return `${path}?${queryStringify}`
                }
            }
            
            const localVarUrlObj = globalImportUrl.parse(localVarPath);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * HomeApi - functional programming interface
 * @export
 */
export const HomeApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 获取首页
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiHomeGet(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => CustomPromise<InlineResponse2002>> {
            const localVarAxiosArgs = await HomeApiAxiosParamCreator(configuration).apiHomeGet(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH):CustomPromise<InlineResponse2002> => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs) as any;
            };
        },
    }
};

/**
 * HomeApi - factory interface
 * @export
 */
export const HomeApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary 获取首页
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiHomeGet(options?: any): Promise<CustomPromise<InlineResponse2002>> {
            return HomeApiFp(configuration).apiHomeGet(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * HomeApi - object-oriented interface
 * @export
 * @class HomeApi
 * @extends {BaseAPI}
 */
export class HomeApi extends BaseAPI {
    /**
     * 
     * @summary 获取首页
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HomeApi
     */
    public apiHomeGet(options?: any) {
        return HomeApiFp(this.configuration).apiHomeGet(options).then((request) => request(this.axios, this.basePath));
    }

}
