// @ts-nocheck
// tslint:disable
/**
 * beacon
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { InlineResponse2002GridBar } from './inline-response2002-grid-bar';
import { InlineResponse2002Swiper } from './inline-response2002-swiper';

/**
 * 
 * @export
 * @interface InlineResponse2002
 */
export interface InlineResponse2002 {
    /**
     * 
     * @type {Array<InlineResponse2002Swiper>}
     * @memberof InlineResponse2002
     */
    swiper?: Array<InlineResponse2002Swiper>;
    /**
     * 
     * @type {Array<InlineResponse2002GridBar>}
     * @memberof InlineResponse2002
     */
    gridBar?: Array<InlineResponse2002GridBar>;
}


