// @ts-nocheck
// tslint:disable
/**
 * beacon
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface InlineResponse2002GridBar
 */
export interface InlineResponse2002GridBar {
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2002GridBar
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2002GridBar
     */
    image: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2002GridBar
     */
    link: string;
}


