export enum ENV {
    DB_TYPE = 'DB_TYPE',
    DB_HOST = 'DB_HOST',
    DB_PORT = 'DB_PORT',
    DB_USERNAME = 'DB_USERNAME',
    DB_PASSWORD = 'DB_PASSWORD',
    DB_DATABASE = 'DB_DATABASE',
    DB_SYNC = 'DB_SYNC',

    REDIS_HOST = 'REDIS_HOST',
    REDIS_PORT = 'REDIS_PORT',
    REDIS_PASSWORD = 'REDIS_PASSWORD',
    REDIS_PREFIX = 'REDIS_PREFIX',

    WX_ACCOUNT_APPID = 'WX_ACCOUNT_APPID',
    WX_ACCOUNT_APPSECRET = 'WX_ACCOUNT_APPSECRET',
}