// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * beacon-umo-client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InlineResponse2001
 */
export interface InlineResponse2001 {
    /**
     * 
     * @type {boolean}
     * @memberof InlineResponse2001
     */
    isLogin: boolean;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2001
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2001
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2001
     */
    avatar?: string;
}

export function InlineResponse2001FromJSON(json: any): InlineResponse2001 {
    return InlineResponse2001FromJSONTyped(json, false);
}

export function InlineResponse2001FromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse2001 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'isLogin': json['isLogin'],
        'username': json['username'],
        'email': json['email'],
        'avatar': !exists(json, 'avatar') ? undefined : json['avatar'],
    };
}

export function InlineResponse2001ToJSON(value?: InlineResponse2001 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'isLogin': value.isLogin,
        'username': value.username,
        'email': value.email,
        'avatar': value.avatar,
    };
}


