// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * beacon-umo-client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TemplateConfigSwiper
 */
export interface TemplateConfigSwiper {
    /**
     * 
     * @type {string}
     * @memberof TemplateConfigSwiper
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof TemplateConfigSwiper
     */
    image: string;
}

export function TemplateConfigSwiperFromJSON(json: any): TemplateConfigSwiper {
    return TemplateConfigSwiperFromJSONTyped(json, false);
}

export function TemplateConfigSwiperFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplateConfigSwiper {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': json['title'],
        'image': json['image'],
    };
}

export function TemplateConfigSwiperToJSON(value?: TemplateConfigSwiper | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'image': value.image,
    };
}


