// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * beacon-umo-client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TemplateConfigGridBar
 */
export interface TemplateConfigGridBar {
    /**
     * 
     * @type {string}
     * @memberof TemplateConfigGridBar
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof TemplateConfigGridBar
     */
    image: string;
    /**
     * 
     * @type {string}
     * @memberof TemplateConfigGridBar
     */
    link: string;
}

export function TemplateConfigGridBarFromJSON(json: any): TemplateConfigGridBar {
    return TemplateConfigGridBarFromJSONTyped(json, false);
}

export function TemplateConfigGridBarFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplateConfigGridBar {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': json['title'],
        'image': json['image'],
        'link': json['link'],
    };
}

export function TemplateConfigGridBarToJSON(value?: TemplateConfigGridBar | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'image': value.image,
        'link': value.link,
    };
}


